name: Deploy Googel Apps Script

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: NPM Install
        id: npm-install
        run: npm i

      - name: lint
        id: eslint
        run: npm run lint

      - name: prettify
        id: prettier
        run: npm run prettier

      - name: Unit Tests
        id: jest
        run: npm t

      - name: NPM Build
        id: npm-build
        run: npm run build

      - name: Install clasp
        id: install-clasp
        run: sudo npm install @google/clasp@2.4.1 -g

      - name: Write CLASPRC_JSON secret to .clasprc.json file
        id: write-clasprc
        run: echo "$CLASPRC_JSON_SECRET" >> ~/.clasprc.json
        env:
          CLASPRC_JSON_SECRET: ${{ secrets.CLASPRC_JSON }}

      - name: Check clasp login status
        id: clasp_login
        run: clasp login --status

      - name: Push script to scripts.google.com
        id: clasp-push
        run: clasp push
